authors:
  equipo:
    name: MinExilon
    description: Administración de MinExilon
    avatar: https://minecraftfaces.com/wp-content/bigfaces/big-steve-face.png
  aaron_el_genio:
    name: aaron_el_genio
    description: Administrador
    avatar: https://crafthead.net/avatar/86daf6dfcc8d4ed3acd744fd02fc1c0a
  TBlackNight:
    name: TBlackNight
    description: Administrador
    avatar: https://crafthead.net/avatar/b8f05d466b8046d1aea1926e557d62ad