authors:
  equipo:
    name: MinExilon
    description: Administración
    avatar: assets/logo_minexilon_cube.png
  aaron_el_genio:
    name: aaron_el_genio
    description: Administrador
    avatar: https://crafthead.net/avatar/86daf6dfcc8d4ed3acd744fd02fc1c0a
  tblacknight:
    name: TBlacKnight
    description: Administrador
    avatar: https://crafthead.net/avatar/b8f05d466b8046d1aea1926e557d62ad